# Generated by Django 4.2 on 2023-04-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('average_cost', models.IntegerField()),
                ('location', models.CharField(max_length=70)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
    ]
